/* ============================================================
   build-mock.mjs — generate _test/admin-mock.html FROM the live
   admin.html so the harness always retests CURRENT code, never a
   stale copy.

   Transforms applied to a fresh read of ../admin.html:
     1. Rewrite the three Firebase gstatic ES-module import URLs to
        ./firebase-mock.js (local mock).
     2. Replace the external <script src="./client.config.js"> (full
        of REPLACE_ME placeholders) with an inline CLIENT config whose
        owners[] includes the mock owner email and a real siteId.
     3. Neutralize the EmailJS CDN <script> (no network in tests) with
        a tiny inline stub that records .send() calls to
        window.__EMAILJS_SENT for assertions.
     4. Inject a small test-instrumentation script (window.__TEST) with
        helpers the audit script uses (current view, force viewport
        classes are unnecessary — CSS handles that via real viewport).

   Run:  node build-mock.mjs
   Output: _test/admin-mock.html
   ============================================================ */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, "..", "admin.html");
const OUT = join(__dirname, "admin-mock.html");

let html = await readFile(SRC, "utf8");

/* 1. Firebase imports -> local mock. All three specifiers resolve to the
   same mock module (its named exports cover app+auth+firestore). */
const before = html;
html = html.replace(
  /https:\/\/www\.gstatic\.com\/firebasejs\/[\d.]+\/firebase-(app|auth|firestore)\.js/g,
  "./firebase-mock.js"
);
if (html === before) {
  console.warn("WARN: no Firebase gstatic import URLs were rewritten — admin.html import lines may have changed.");
}

/* 2. Replace external client.config.js with an inline CLIENT config. */
const clientShim = `<script>
window.CLIENT = {
  siteId: "test-site",
  owners: ["carsonhanna5@gmail.com", "owner@broskisdetail.com"],
  firebase: { apiKey: "mock", authDomain: "mock", projectId: "mock", storageBucket: "mock", messagingSenderId: "mock", appId: "mock" },
  accent: "#2563EB",
  map: { center: [39.878, -104.985], radius: 17000, cities: [] },
  phoneRaw: "+17205550184"
};
</script>`;
const cfgBefore = html;
html = html.replace(/<script src="\.\/client\.config\.js"><\/script>/, clientShim);
if (html === cfgBefore) console.warn("WARN: client.config.js script tag not found/replaced.");

/* 2b. content.js ships as a plain <script> (not a module) adjacent to admin.html.
   admin-mock.html lives in _test/, so ./content.js would resolve to _test/content.js
   (wrong). Rewrite to ../content.js so the mock picks up the real file. */
const cjsBefore = html;
html = html.replace(/<script src="\.\/content\.js"><\/script>/, `<script src="../content.js"></script>`);
if (html === cjsBefore) console.warn("WARN: content.js script tag not found/rewritten — admin.html may have changed.");

/* 3. Neutralize EmailJS CDN script with a recording stub. */
const emailStub = `<script>
window.emailjs = {
  __sent: (window.__EMAILJS_SENT = []),
  send: function (service, template, params) {
    window.__EMAILJS_SENT.push({ service: service, template: template, params: params });
    return Promise.resolve({ status: 200, text: "OK (mock)" });
  },
  init: function () {}
};
</script>`;
const ejBefore = html;
html = html.replace(/<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/@emailjs\/browser[^"]*"><\/script>/, emailStub);
if (html === ejBefore) console.warn("WARN: EmailJS CDN script tag not found/replaced.");

/* 4. Test instrumentation — exposes the module's internal state minimally.
   admin.html is a self-contained module (no exports), so we can only
   observe via the DOM. This just tags the doc so the audit knows it is
   the mock build and can wait on it. */
const testBanner = `<!-- GENERATED BY _test/build-mock.mjs FROM ../admin.html — DO NOT EDIT BY HAND -->\n`;
const instrument = `<script>window.__ADMIN_MOCK = true;</script>\n`;
html = testBanner + html.replace("</body>", instrument + "</body>");

await writeFile(OUT, html, "utf8");
console.log("Wrote", OUT, "(" + html.length + " bytes)");
